spring.application.name=config-server

#mentioning that from where it can get the configurations
spring.profiles.active=native
#telling that the config folder contains all the configurations
spring.cloud.config.server.native.search-locations=classpath:/config

server.port=8888