

server.port=8081

spring.datasource.url=jdbc:postgresql://postgres:5432/fitness_user_db
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.database-platform=org.hibernate.dialect.PostgreSQLDialect


eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
