

server.port=8081

spring.datasource.url= jdbc:postgresql://localhost:5432/fitness_user_db
spring.datasource.username=postgres
spring.datasource.password=Ks120@120

spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.database-platform=org.hibernate.dialect.PostgreSQLDialect


eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
