spring.application.name=eureka

server.port=8761

# i dont want to register the eureka with any other server.
eureka.client.register-with-eureka=false 
#this server doesnt fetch other instances from eureka server
eureka.client.fetch-registry=false

